# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Download this notebook for our code-along:

From our class GitHub repository "notebooks" directory, download the file "02_numpy_and_pandas.ipynb".  Move this to a convenient place where you are grouping your class related materials.


# Introduction to Numpy ("num-pi")

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why use the Numpy package for Data?
    * It makes our data science life easier!!
        * Numpy brings *decades* of C math into Python!
        * Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
        * NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [1]:
## from numpy import * #Load all the numpy packages
%matplotlib inline
import numpy as np



### A Note About "import as"

    import * 
This loads all submodules. Note: this is a waste of memory when incorporated into deployed code. 
We'll use it here by example - it's fine to use for learning purposes and legibility.

As we'll see later, the proper convention is to use:

    import numpy as np
    
And then to specifically call needed methods:

![](https://www.evernote.com/shard/s97/sh/7b2e1c08-16c3-4cef-9d9d-b329c3559972/b0e9440ee858b94049b37b0308afd2eb/deep/0/lec_03_numpy_and_pandas_draft.png)

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [2]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

What are these functions?

    arange?

In [3]:
# Note the way each array is printed:
print("a: ",a)
print("b: ",b)
print("c: ",c)
print("d: ",d)

('a: ', array([ 0.,  0.,  0.]))
('b: ', array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]]))
('c: ', array([[[4, 9, 3, 1],
        [3, 5, 9, 1],
        [6, 3, 9, 6]],

       [[7, 5, 2, 3],
        [8, 1, 9, 3],
        [4, 2, 7, 8]]]))
('d: ', array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))


In [4]:
## Arithmetic in arrays is element wise

In [5]:
>>> a = np.array( [20,30,40,50] )
>>> b = np.arange( 4 )
>>> b

array([0, 1, 2, 3])

In [6]:
>>> c = a-b
>>> c

array([20, 29, 38, 47])

In [7]:
>>> b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [8]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [9]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
a[2:5]

array([ 4,  9, 16])

In [11]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [12]:
b = np.random.randint(1,100,(4,4))

In [13]:
b

array([[ 6, 45, 13, 46],
       [87, 19, 33, 85],
       [74, 63, 52, 42],
       [26, 41, 63, 56]])

In [14]:
# Guess the output
print(b[2,3])


42


In [15]:
# Guess the output
print(b[0,0])


6


In [16]:
# Guess the output
b[0:3,1]

array([45, 19, 63])

In [17]:
#Guess the output
b[:,1]

array([45, 19, 63, 41])

In [18]:
#Guess the output
b[1:3,:]

array([[87, 19, 33, 85],
       [74, 63, 52, 42]])

# Introduction to Pandas

**Pandas, Know it! Love it! We will use it extensively.**

Will allow us to use short lines of code to do important manipulation and viewing of our data
* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [21]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [22]:
# Index, columns, underlying numpy data
df

A         B         C         D
2014-01-01  0.330651 -0.324660 -0.398121 -0.092536
2014-01-02 -1.463100  0.449010  0.927521  0.576199
2014-01-03 -1.034998 -2.807361 -0.650076  0.478049
2014-01-04 -0.194769  0.738137 -0.523797  0.495508
2014-01-05  0.814008  0.007345 -0.999315  0.514622
2014-01-06  1.470670 -0.471033 -1.468652 -0.419098

In [23]:
df.T


2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A    0.330651   -1.463100   -1.034998   -0.194769    0.814008    1.470670
B   -0.324660    0.449010   -2.807361    0.738137    0.007345   -0.471033
C   -0.398121    0.927521   -0.650076   -0.523797   -0.999315   -1.468652
D   -0.092536    0.576199    0.478049    0.495508    0.514622   -0.419098

In [24]:
df

A         B         C         D
2014-01-01  0.330651 -0.324660 -0.398121 -0.092536
2014-01-02 -1.463100  0.449010  0.927521  0.576199
2014-01-03 -1.034998 -2.807361 -0.650076  0.478049
2014-01-04 -0.194769  0.738137 -0.523797  0.495508
2014-01-05  0.814008  0.007345 -0.999315  0.514622
2014-01-06  1.470670 -0.471033 -1.468652 -0.419098

In [25]:
temp = df.T
temp

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A    0.330651   -1.463100   -1.034998   -0.194769    0.814008    1.470670
B   -0.324660    0.449010   -2.807361    0.738137    0.007345   -0.471033
C   -0.398121    0.927521   -0.650076   -0.523797   -0.999315   -1.468652
D   -0.092536    0.576199    0.478049    0.495508    0.514622   -0.419098

In [26]:
df = df.T

In [27]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [28]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [29]:
df

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A    0.330651   -1.463100   -1.034998   -0.194769    0.814008    1.470670
B   -0.324660    0.449010   -2.807361    0.738137    0.007345   -0.471033
C   -0.398121    0.927521   -0.650076   -0.523797   -0.999315   -1.468652
D   -0.092536    0.576199    0.478049    0.495508    0.514622   -0.419098

In [30]:
df.head(1)

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A    0.330651     -1.4631   -1.034998   -0.194769    0.814008     1.47067

In [31]:
df.tail(3)

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
B   -0.324660    0.449010   -2.807361    0.738137    0.007345   -0.471033
C   -0.398121    0.927521   -0.650076   -0.523797   -0.999315   -1.468652
D   -0.092536    0.576199    0.478049    0.495508    0.514622   -0.419098

In [32]:
df.index

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [33]:
df.describe()

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
count    4.000000    4.000000    4.000000    4.000000    4.000000    4.000000
mean    -0.121167    0.122408   -1.003597    0.128770    0.084165   -0.222028
std      0.328163    1.076203    1.363183    0.587749    0.795360    1.227482
min     -0.398121   -1.463100   -2.807361   -0.523797   -0.999315   -1.468652
25%     -0.343026   -0.029017   -1.478089   -0.277026   -0.244320   -0.720437
50%     -0.208598    0.512605   -0.842537    0.150370    0.260984   -0.445065
75%      0.013261    0.664030   -0.368045    0.556165    0.589468    0.053344
max      0.330651    0.927521    0.478049    0.738137    0.814008    1.470670

In [34]:
df

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A    0.330651   -1.463100   -1.034998   -0.194769    0.814008    1.470670
B   -0.324660    0.449010   -2.807361    0.738137    0.007345   -0.471033
C   -0.398121    0.927521   -0.650076   -0.523797   -0.999315   -1.468652
D   -0.092536    0.576199    0.478049    0.495508    0.514622   -0.419098

In [35]:
z = df.sort_values(by="B")
z


KeyError: 'B'

### Selection

In [ ]:
df[['A','B']]

In [ ]:
df[0:3]

In [ ]:
# By label
df.loc[dates[0]]

In [ ]:
# multi-axis by label
df.loc[:,['A','B']]

In [ ]:
# Date Range
df.loc['20140102':'20140104',['B']]

In [ ]:
# Fast access to scalar
df.at[dates[1],'B']

### Operations

In [ ]:
df.describe()

In [ ]:
df.mean(),df.mean(1) # Operation on two different axes
# there are pandas' methods for min, max etc. as well

### Boolean Indexing

In [ ]:
df

In [ ]:
df[df.A < 0] # Basically a 'where' operation

In [ ]:
df.A < 0

In [ ]:
# Two conditions added together
df[(df.A < 0) & (df.B > .5) ]

In [ ]:
# Two conditions ORed together
df[(df.A < -1) | (df.D > 0)]

### Merge

In [ ]:
np.random.randn(10,4)

In [ ]:
##Concatenating pandas objects together
# create a dataframe to use as an example
df2 = pd.DataFrame(np.random.randn(10,4))
df2

In [ ]:
# Break it into pieces
pieces = [df2[:3], df2[3:7],df2[7:]]
pieces

In [ ]:
pd.concat(pieces, axis = 1)

In [ ]:
# Also can "Join" and "Append"

### Setting

In [ ]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [ ]:
df_posA

In [ ]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [ ]:
s1

In [ ]:
df['F'] = s1

In [ ]:
df

### Missing Data

In [ ]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [ ]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [ ]:
df1

In [ ]:
# find where values are null
pd.isnull(df1)

### Applying functions

In [ ]:
df

In [ ]:
df.apply(np.cumsum)

In [ ]:
df.apply(lambda x: x.max() - x.min())

In [ ]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

### Grouping


In [ ]:
df3 = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [ ]:
df3

In [ ]:
df3.groupby(['A','B']).sum()

### Reshaping

In [ ]:
# You can also stack or unstack levels

In [ ]:
a = df3.groupby(['A','B']).sum()

In [ ]:
# Pivot Tables
# pd.pivot_table(df3,values=['C','D'],rows=['A'],cols=['B'])

### Time Series


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [ ]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts

In [ ]:
# Built in resampling
ts.resample('1Min',how='mean') # Resample secondly to 1Minutely

In [ ]:
# Many additional time series features
# ts. #use tab

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/tutorials.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas